/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import Jogos.Acerte_Numero;
import Jogos.Forca;
import Jogos.Impar_Par.Impar_Par_Sorteio;
import Jogos.Jokenpo;
import Jogos.Quiz;
import Jogos.Jogo_Da_Velha;
import Extras.Criadores;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Zile
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Multplayer
     */
    public Menu_Principal() {
        initComponents();
        Dimension maxDimension = new Dimension(500, 600);
        this.setMaximumSize(maxDimension);

// Impede que o usuário redimensione a janela
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_acertenum = new javax.swing.JToggleButton();
        btn_forca = new javax.swing.JToggleButton();
        btn_quiz = new javax.swing.JToggleButton();
        btn_velha = new javax.swing.JToggleButton();
        btn_jokenpo = new javax.swing.JToggleButton();
        btn_impapar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        jPasswordField1.setText("jPasswordField1");

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 42, 42));
        setSize(new java.awt.Dimension(500, 550));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_acertenum.setBackground(new java.awt.Color(255, 255, 255));
        btn_acertenum.setForeground(new java.awt.Color(0, 0, 0));
        btn_acertenum.setText("Acerte o Numero");
        btn_acertenum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_acertenumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_acertenumMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_acertenumMouseReleased(evt);
            }
        });
        btn_acertenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acertenumActionPerformed(evt);
            }
        });

        btn_forca.setBackground(new java.awt.Color(255, 255, 255));
        btn_forca.setForeground(new java.awt.Color(0, 0, 0));
        btn_forca.setText("Forca");
        btn_forca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_forcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_forcaMouseExited(evt);
            }
        });
        btn_forca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forcaActionPerformed(evt);
            }
        });

        btn_quiz.setBackground(new java.awt.Color(255, 255, 255));
        btn_quiz.setForeground(new java.awt.Color(0, 0, 0));
        btn_quiz.setText("Quiz");
        btn_quiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_quizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_quizMouseExited(evt);
            }
        });
        btn_quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quizActionPerformed(evt);
            }
        });

        btn_velha.setBackground(new java.awt.Color(255, 255, 255));
        btn_velha.setForeground(new java.awt.Color(0, 0, 0));
        btn_velha.setText("Jogo Da Velha");
        btn_velha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_velhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_velhaMouseExited(evt);
            }
        });
        btn_velha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_velhaActionPerformed(evt);
            }
        });

        btn_jokenpo.setBackground(new java.awt.Color(255, 255, 255));
        btn_jokenpo.setForeground(new java.awt.Color(0, 0, 0));
        btn_jokenpo.setText("Jokenpo");
        btn_jokenpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jokenpoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jokenpoMouseExited(evt);
            }
        });
        btn_jokenpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jokenpoActionPerformed(evt);
            }
        });

        btn_impapar.setBackground(new java.awt.Color(255, 255, 255));
        btn_impapar.setForeground(new java.awt.Color(0, 0, 0));
        btn_impapar.setText("Impa Ou Par");
        btn_impapar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_impaparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_impaparMouseExited(evt);
            }
        });
        btn_impapar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_impaparActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione Um Jogo");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("?");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_acertenum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_velha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_impapar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_forca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jokenpo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_acertenum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_velha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_forca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_impapar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jokenpo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acertenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acertenumActionPerformed
        Acerte_Numero jogo = new Acerte_Numero();

        // Chame o método iniciarJogo do objeto
        Acerte_Numero.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btn_acertenumActionPerformed

    private void btn_forcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forcaActionPerformed
        Forca jogo = new Forca();

        // Chame o método iniciarJogo do objeto
        Forca.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btn_forcaActionPerformed

    private void btn_quizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quizActionPerformed
        // TODO add your handling code here:
        Quiz jogo = new Quiz();

        // Chame o método iniciar Jogo do objeto
        Quiz.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btn_quizActionPerformed

    private void btn_velhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_velhaActionPerformed
        // TODO add your handling code here:
        Jogo_Da_Velha jogo = new Jogo_Da_Velha();

        // Chame o método iniciarJogo do objeto
        Jogo_Da_Velha.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btn_velhaActionPerformed

    private void btn_jokenpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jokenpoActionPerformed
        // TODO add your handling code here:
        Jokenpo jogo = new Jokenpo();

        // Chame o método iniciarJogo do objeto
        Jokenpo.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btn_jokenpoActionPerformed

    private void btn_impaparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_impaparActionPerformed

// TODO add your handling code here:
        Impar_Par_Sorteio jogo = new Impar_Par_Sorteio();

        // Start the Quiz game and dispose the current window
        Impar_Par_Sorteio.main(new String[]{});

        this.dispose();
    }//GEN-LAST:event_btn_impaparActionPerformed

    private void btn_acertenumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acertenumMouseReleased
        // TODO add your handling code here:
        btn_acertenum.setBackground(Color.BLUE);
    }//GEN-LAST:event_btn_acertenumMouseReleased

    private void btn_acertenumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acertenumMouseEntered
        // TODO add your handling code here:
        btn_acertenum.setBackground(new Color(102, 102, 102, 110));
        btn_acertenum.setForeground(new Color(255, 255, 255, 255));
    }//GEN-LAST:event_btn_acertenumMouseEntered

    private void btn_acertenumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acertenumMouseExited
        // TODO add your handling code here:
        btn_acertenum.setBackground(Color.WHITE);
        btn_acertenum.setForeground(new Color(0, 0, 0, 255));
    }//GEN-LAST:event_btn_acertenumMouseExited

    private void btn_quizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quizMouseEntered
        // TODO add your handling code here:
        btn_quiz.setBackground(new Color(102, 102, 102, 255));
        btn_quiz.setForeground(new Color(255, 255, 255, 255));
    }//GEN-LAST:event_btn_quizMouseEntered

    private void btn_quizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quizMouseExited
        // TODO add your handling code here:
        btn_quiz.setBackground(Color.WHITE);
        btn_quiz.setForeground(new Color(0, 0, 0, 255));
    }//GEN-LAST:event_btn_quizMouseExited

    private void btn_velhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_velhaMouseEntered
        // TODO add your handling code here:
        btn_velha.setBackground(new Color(102, 102, 102, 255));
        btn_velha.setForeground(new Color(255, 255, 255, 255));
    }//GEN-LAST:event_btn_velhaMouseEntered

    private void btn_forcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_forcaMouseEntered
        // TODO add your handling code here:
        btn_forca.setBackground(new Color(102, 102, 102, 255));
        btn_forca.setForeground(new Color(255, 255, 255, 255));
    }//GEN-LAST:event_btn_forcaMouseEntered

    private void btn_jokenpoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jokenpoMouseEntered
        // TODO add your handling code here:
        btn_jokenpo.setBackground(new Color(102, 102, 102, 255));
        btn_jokenpo.setForeground(new Color(255, 255, 255, 255));
    }//GEN-LAST:event_btn_jokenpoMouseEntered

    private void btn_impaparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impaparMouseEntered
        // TODO add your handling code here:
        btn_impapar.setBackground(new Color(102, 102, 102, 255));
        btn_impapar.setForeground(new Color(255, 255, 255, 255));
    }//GEN-LAST:event_btn_impaparMouseEntered

    private void btn_velhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_velhaMouseExited
        // TODO add your handling code here:
        btn_velha.setBackground(Color.WHITE);
        btn_velha.setForeground(new Color(0, 0, 0, 255));
    }//GEN-LAST:event_btn_velhaMouseExited

    private void btn_forcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_forcaMouseExited
        // TODO add your handling code here:
        btn_forca.setBackground(Color.WHITE);
        btn_forca.setForeground(new Color(0, 0, 0, 255));
    }//GEN-LAST:event_btn_forcaMouseExited

    private void btn_jokenpoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jokenpoMouseExited
        // TODO add your handling code here:
        btn_jokenpo.setBackground(Color.WHITE);
        btn_jokenpo.setForeground(new Color(0, 0, 0, 255));
    }//GEN-LAST:event_btn_jokenpoMouseExited

    private void btn_impaparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_impaparMouseExited
        // TODO add your handling code here:
        btn_impapar.setBackground(Color.WHITE);
        btn_impapar.setForeground(new Color(0, 0, 0, 255));
    }//GEN-LAST:event_btn_impaparMouseExited

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        Criadores Extras = new Criadores();

        Criadores.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_acertenum;
    private javax.swing.JToggleButton btn_forca;
    private javax.swing.JToggleButton btn_impapar;
    private javax.swing.JToggleButton btn_jokenpo;
    private javax.swing.JToggleButton btn_quiz;
    private javax.swing.JToggleButton btn_velha;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
