/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.forca;

import Menus.Menu_Principal;
import static com.mycompany.forca.Forca_Palavra.palavra;
import static com.mycompany.forca.Forca_Palavra.dica;
import javax.swing.JOptionPane;

/**
 *
 * @author Zile
 */
public class Forca_Jogo extends javax.swing.JFrame {

    int contador = 0;

    /**
     * Creates new form Forca
     */
    public Forca_Jogo() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        label_letras.setText("");
        String palavraFormatada = formatarPalavra(palavra);
        label_palavra.setText(palavraFormatada);
        label_dica.setText("A dica é: " + dica);
        label_cabeca.setVisible(false);
        label_pd.setVisible(false);
        label_pe.setVisible(false);
        label_corpo.setVisible(false);
        label_be.setVisible(false);
        label_bd.setVisible(false);
        btn_recomecar.setVisible(false);
    }

    // Método para formatar a palavra com underscores
    private String formatarPalavra(String palavra) {
        StringBuilder palavraFormatada = new StringBuilder();
        for (int i = 0; i < palavra.length(); i++) {
            palavraFormatada.append("_ ");
        }
        return palavraFormatada.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_palavra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_dica = new javax.swing.JLabel();
        input_letra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        label_letras = new javax.swing.JLabel();
        btn_recomecar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_cabeca = new javax.swing.JLabel();
        label_corpo = new javax.swing.JLabel();
        label_pe = new javax.swing.JLabel();
        label_be = new javax.swing.JLabel();
        label_bd = new javax.swing.JLabel();
        label_pd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel3.setText("jLabel3");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("|");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        label_palavra.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        label_palavra.setForeground(new java.awt.Color(102, 51, 0));
        label_palavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_palavra.setText("palavra");

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jogo da forca");

        label_dica.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        label_dica.setForeground(new java.awt.Color(102, 51, 0));
        label_dica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dica.setText("A dica é: ");

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insira uma letra");

        btn_enviar.setBackground(new java.awt.Color(255, 255, 255));
        btn_enviar.setForeground(new java.awt.Color(102, 51, 0));
        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        label_letras.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        label_letras.setForeground(new java.awt.Color(102, 51, 0));
        label_letras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_letras.setText(".");

        btn_recomecar.setBackground(new java.awt.Color(255, 255, 255));
        btn_recomecar.setForeground(new java.awt.Color(102, 51, 0));
        btn_recomecar.setText("Recomeçar");
        btn_recomecar.setToolTipText("");
        btn_recomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recomecarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 0));

        label_cabeca.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label_cabeca.setForeground(new java.awt.Color(102, 51, 0));
        label_cabeca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_cabeca.setText("0");

        label_corpo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label_corpo.setForeground(new java.awt.Color(102, 51, 0));
        label_corpo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_corpo.setText("|");

        label_pe.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label_pe.setForeground(new java.awt.Color(102, 51, 0));
        label_pe.setText("/");

        label_be.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label_be.setForeground(new java.awt.Color(102, 51, 0));
        label_be.setText("/");

        label_bd.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        label_bd.setForeground(new java.awt.Color(102, 51, 0));
        label_bd.setText("\\");

            label_pd.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
            label_pd.setForeground(new java.awt.Color(102, 51, 0));
            label_pd.setText("\\");

                jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(102, 51, 0));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("forca");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(102, 51, 0));
                jLabel6.setText("-");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(102, 51, 0));
                jLabel7.setText("-");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel8.setForeground(new java.awt.Color(102, 51, 0));
                jLabel8.setText("-");

                jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(102, 51, 0));
                jLabel10.setText("|");

                jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(102, 51, 0));
                jLabel11.setText("-");

                jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(102, 51, 0));
                jLabel12.setText("|");

                jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel14.setForeground(new java.awt.Color(102, 51, 0));
                jLabel14.setText("|");

                jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel15.setForeground(new java.awt.Color(102, 51, 0));
                jLabel15.setText("|");

                jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel16.setForeground(new java.awt.Color(102, 51, 0));
                jLabel16.setText("|");

                jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel17.setForeground(new java.awt.Color(102, 51, 0));
                jLabel17.setText("|");

                jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel18.setForeground(new java.awt.Color(102, 51, 0));
                jLabel18.setText("|");

                jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                jLabel19.setForeground(new java.awt.Color(102, 51, 0));
                jLabel19.setText("|");

                jButton1.setBackground(new java.awt.Color(255, 255, 255));
                jButton1.setForeground(new java.awt.Color(102, 51, 0));
                jButton1.setText(" ↲");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(label_be, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_bd))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(label_pe))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(label_corpo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label_pd))))
                                    .addComponent(label_cabeca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label_pe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_corpo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_pd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(label_be, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_bd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(label_cabeca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_dica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_letras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_palavra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(input_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_recomecar))
                                .addGap(61, 61, 61)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(label_dica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_palavra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_letras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_enviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_recomecar))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        String letra = input_letra.getText();
        input_letra.setText("");

// Verifica se foi digitada apenas uma letra
        if (letra.length() != 1) {
            JOptionPane.showMessageDialog(this, "Digite apenas uma letra por vez.");
            return;
        }

// Verifica se a letra é válida (uma letra do alfabeto)
        if (!letra.matches("[a-zA-Z]")) {
            JOptionPane.showMessageDialog(this, "Digite apenas letras do alfabeto.");
            return;
        }

// Verifica se a letra já foi digitada anteriormente
        if (label_letras.getText().contains(letra)) {
            JOptionPane.showMessageDialog(this, "A letra '" + letra + "' já foi digitada anteriormente.");
            return;
        }

        boolean letraEncontrada = false;

        for (int i = 0; i < palavra.length(); i++) {
            if (palavra.charAt(i) == letra.charAt(0)) {
                StringBuilder palavraAtualizada = new StringBuilder(label_palavra.getText());
                palavraAtualizada.setCharAt(i * 2, letra.charAt(0)); // Atualiza a letra na posição correta
                label_palavra.setText(palavraAtualizada.toString());
                letraEncontrada = true;
            }
        }

        if (!letraEncontrada) {
            contador++;

            String letrasErradas = label_letras.getText();
            if (!letrasErradas.isEmpty()) {
                letrasErradas += "-";
            }
            letrasErradas += letra;
            label_letras.setText(letrasErradas);
        }

        if (label_palavra.getText().replaceAll(" ", "").equals(palavra)) {
            JOptionPane.showMessageDialog(this, "Parabéns! Você venceu o jogo!");
            btn_recomecar.setVisible(true);
            btn_enviar.setVisible(false);
            input_letra.setVisible(false);
            // Aqui você pode adicionar a lógica para reiniciar o jogo ou encerrar o programa
        }

        if (contador == 1) {
            label_cabeca.setVisible(true);
        } else if (contador == 2) {
            label_corpo.setVisible(true);
        } else if (contador == 3) {
            label_be.setVisible(true);
        } else if (contador == 4) {
            label_bd.setVisible(true);
        } else if (contador == 5) {
            label_pe.setVisible(true);
        } else if (contador == 6) {
            label_pd.setVisible(true);
            JOptionPane.showMessageDialog(this, "Derrota! o numero de erros foi atingido!");
            btn_recomecar.setVisible(true);
            btn_enviar.setVisible(false);
            input_letra.setVisible(false);
        }
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_recomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recomecarActionPerformed
        // TODO add your handling code here:
        Forca_Palavra jogos = new Forca_Palavra();

        // Começa o Jogo e fecha a janela atual
        Forca_Palavra.main(new String[]{});

        this.dispose();
    }//GEN-LAST:event_btn_recomecarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        // cria e exibe a janela "solo"
        Menu_Principal Menu_Principal = new Menu_Principal();
        Menu_Principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forca_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forca_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forca_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forca_Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forca_Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_recomecar;
    private javax.swing.JTextField input_letra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_bd;
    private javax.swing.JLabel label_be;
    private javax.swing.JLabel label_cabeca;
    private javax.swing.JLabel label_corpo;
    private javax.swing.JLabel label_dica;
    private javax.swing.JLabel label_letras;
    private javax.swing.JLabel label_palavra;
    private javax.swing.JLabel label_pd;
    private javax.swing.JLabel label_pe;
    // End of variables declaration//GEN-END:variables
}
